### ISSUE TITLE
Limit number of days

### ISSUE THREAD

**Issue by SdeGeata** [jclarke0000/MMM-DarkSkyForecast#24]
Hello!

So I enjoy your module, but I was just wondering how I could limit the number of days to show. Right now it shows three entries for today, plus the next 4 days. I would like to limit that to the same three entries for hourly today, then the next 3 days rather than 4. I couldn't find an option in the config guide. Is there a way?

**Comment by robertalexa** [comment]
Check the documentation for: maxDailiesToShow

Hope this helps

**Comment by SdeGeata** [comment]
Hello Robert Alexa:

Thanks for the hint. I searched to documentation for a parameter, I don't know how I missed that one. Thanks!
