### ISSUE TITLE
Apple has purchased Dark Sky and is shutting down the API

### ISSUE THREAD

**Issue by tinohager** [jclarke0000/MMM-DarkSkyForecast#27]
Apple has purchased Dark Sky and is shutting down the API.
The API will continue to function through the end of 2021.
[More Informations](https://blog.darksky.net/)

**Comment by daymo87** [comment]
gutted about this had just installed it glad i left apple!

**Comment by ghost** [comment]
Too bad, I was looking forward to use the module :(

Maybe this could help, to create a new version soon:
https://openweathermap.org/darksky-openweather
https://openweathermap.org/darksky-openweather#match

**Comment by handwrittenjello** [comment]
Looks like there was a PR #29  Submitted to fix this issue.

**Comment by lxne** [comment]
API will work one more year.
Till end of 2022.
https://blog.darksky.net
