### ISSUE TITLE
hourlyForecastInterval doesn't work

### ISSUE THREAD

**Issue by Obelix74Git** [jclarke0000/MMM-DarkSkyForecast#3]
first of all, great that you made a new weather module like MMM-WunderGround. I really liked that one.

I have a problem with hourlyForecastInterval. If I don't put it in de config and leave it to the default and put maxHourliesToShow : "6", in the config, than I receive 6 forecasts with 3 hours apart. 
When I put hourlyForecastInterval to 1 or 2 I only get 2 forecasts that are 10 hours apart.

**Comment by jclarke0000** [comment]
This came up before because the value was specified as a string in the config when the module expected an integer.  I've since made an update to the module to accept strings as values.
