### ISSUE TITLE
Remove npm from dependency list

### ISSUE THREAD

**Issue by michael5r** [jclarke0000/MMM-DarkSkyForecast#4]
![image](https://user-images.githubusercontent.com/3209660/49700666-71134a80-fba7-11e8-85f5-3785c93a6e25.png)

`npm` should **never** be included as a dependency in a package - it's entirely reliant on the version of node you have installed.

**Comment by jclarke0000** [comment]
npm wasn't added explicitly.  It got added I'm assuming when I included one of the others.  It's possible that a specific version of npm is required in order to install one of the other dependencies.  Leaving this in place.
