### ISSUE TITLE
Stuck "Loading ..." forever. No weather is displayed

### ISSUE THREAD

**Issue by hco125** [jclarke0000/MMM-DarkSkyForecast#6]
MagicMirror version: 2.5.0

Node Version: 10.15.0

MMM-DarkSkyForecast version: 1.0.0

Screenshot of problem:
![capture](https://user-images.githubusercontent.com/45411481/50539971-c3181200-0b4e-11e9-8bb1-a0dbbe09410a.PNG)

Config.js configuration:
```
		{
			module: 'MMM-DarkSkyForecast',
			header: "Weather",
			position: 'top_center',
			disabled: false,
			config: {
				updateInterval: 10,
				//requestDelay: 250,
				//updateFadeSpeed: 500,
				//language: 'en',
				//colored: true,
				units: 'us',
				//showCurrentConditions: true,
				//showExtraCurrentConditions: true,
				//showSummary: true,
				forecastHeaderText: "O'Neill, NE",
				//showForecastTableColumnHeaderIcons: true,
				//showHourlyForecast: true,
				hourlyForecastInterval: 2,
				maxHourliesToShow: 5,
				//showDailyForecast: true,
				maxDailiesToShow: 5,
				//showPrecipitation: true,
				//showWind: true,
				//concise: true,
				iconset: '5c',
				apiKey: 'blocked for privacy',
				latitude: '42.457649',
				longitude: '-98.647789',
				//useAnimatedIcons: true,
				forecastLayout: 'tiled',
				//showInlineIcons: true,
			},
               },
```

**Comment by hco125** [comment]
We can close this issue now. I figured out that I am an idiot. I typed "apiKey" in the configuration, rather than "apikey". Fixed it and it works now. Sorry for taking your time.
![weather](https://user-images.githubusercontent.com/45411481/50804579-3854b700-12b4-11e9-9926-ab9dc9ffb6c2.png)

**Comment by CatoAntonsen** [comment]
Ok, now *I'M* an idiot! Is't what you *first* wrote, the *SAME* as what you say you should write???
